image: registry.gitlab.rozetka.company/common/ci-docker-images/ci-deployer-php74:latest

variables:
  #for RABBITMQ
  CONFIGURATION_MESSAGEBUS_HOST: selfi-rabbitmq
  CONFIGURATION_MESSAGEBUS_LOGIN: guest
  CONFIGURATION_MESSAGEBUS_PASSWORD: guest
  CONFIGURATION_MESSAGEBUS_ROUTINGKEY: '#'
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  TELEGRAM_CHAT_ID: "-1001552457457"

before_script:
  - export VAULT_ADDR=https://vault.rozetka.company:8200
  - vault read -field=PROD_PRIVATE devops/infra/rzk > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa

stages:
  - build
  - run_autotest
  - report
  - deploy
  - rollback
  - stop-restart
  - start

build:
  image: registry.gitlab.rozetka.company/ivv/nimble/php-ci:1.1
  stage: build
  tags:
    - kube-prod
  before_script:
    - curl http://repo.dev.rozetka.com.ua/devops/vault-1.3.2 --output /bin/vault
    - chmod a+x /bin/vault
    - curl http://repo.dev.rozetka.com.ua/devops/deployer.phar-6.8.0 --output /bin/dep --silent
    - chmod a+x /bin/dep
    - git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    - mkdir /root/.ssh
    - chmod 600 /root/.ssh
    - export VAULT_ADDR=https://vault.rozetka.company:8200
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=nimble-staging jwt=$CI_JOB_JWT)"
    - vault read -field=PROD_PRIVATE devops/infra/rzk > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
  script:
    - cp env.test-default .env.test
    - cp env.test-default .env
    - composer install
  only:
    - branches
    - tags
  when: always
  artifacts:
    paths:
      - vendor/
    expire_in: 1 day

run_autotest:
  image: registry.gitlab.rozetka.company/ivv/nimble/php-ci:1.1
  stage: run_autotest
  except:  [tags]
  tags:
    - kube-prod
  services:
    - name: registry.gitlab.rozetka.company/ivv/nimble/php-ci:1.1
      alias: php
    - name: registry.gitlab.rozetka.company/ivv/nimble/nginx-ci:1.0
    # alias: product-api-dev.rozetka.com.ua
    - name: registry.gitlab.rozetka.company/ivv/nimble/postgre-ci:1.0
      alias: selfi-postgre
    - name: redis
      alias: redis
    - name: jamesdbloom/mockserver:latest
      alias: mock-server
    - name: rabbitmq:3.6-management-alpine
      alias: selfi-rabbitmq
  before_script:
    - curl http://repo.dev.rozetka.com.ua/devops/vault-1.3.2 --output /bin/vault
    - chmod a+x /bin/vault
    - curl http://repo.dev.rozetka.com.ua/devops/deployer.phar-6.8.0 --output /bin/dep
    - chmod a+x /bin/dep
    - git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    - mkdir /root/.ssh
    - chmod 600 /root/.ssh
    - export VAULT_ADDR=https://vault.rozetka.company:8200
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=nimble-staging jwt=$CI_JOB_JWT)"
    - vault read -field=PROD_PRIVATE devops/infra/rzk > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
  script:
    - cp env.test-default .env.test
    - cp env.test-default .env
    - php artisan migrate
    - sleep 10
    - vendor/bin/codecept run -c vendor/ivv/nimble-test -g api --html
  only:
    - branches
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/runtime
      - ${CI_PROJECT_DIR}/console/runtime
      - ${CI_PROJECT_DIR}/vendor/ivv/nimble-test/tests/_output/allure-results
    expire_in: 1 week

report:
  image: registry.gitlab.rozetka.company/automation-testing-tools/ci-helper-front:allure1.1
  stage: report
  except: [ tags ]
  before_script:
    - echo
  cache: { }
  tags:
    - kube-prod
  when: always
  script:
    - allure generate --clean ${CI_PROJECT_DIR}/vendor/ivv/nimble-test/tests/_output/allure-results --report-dir ${CI_PROJECT_DIR}/allure-report
  only:
    - branches
  artifacts:
    when: always
    paths:
      - ./allure-report
    expire_in: 1 week


deploy-dev:
  stage: deploy
  tags:
    - rozetka-shared-standart
  script:
    - consul-template -template "env.dev:.env" -once
    - dep build dev  -p -vv
    - dep deploy dev  -p -vv
  when: manual
  only:
    - branches
  except:
    - master


stop-dev-ms:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:stop dev -p -vv
  when: manual
  only:
    - branches
  except:
    - master


stop-dev-gs:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:stop dev -p -vv
  when: manual
  only:
    - branches
  except:
    - master

deploy-prod:
  stage: deploy
  tags:
    - rozetka-shared-standart
  script:
    - consul-template -template "env.prod:.env" -once
    - dep build prod -p -vv
    - curl -X POST -H "Content-Type:application/json" -d "{\"alias\":\"gitlab\",\"text\":\"* ${CI_PROJECT_NAME}:*   пользователь *${GITLAB_USER_LOGIN}* запустил деплой  \nversion:*$CI_COMMIT_REF_NAME* \npipeline:${CI_PROJECT_URL}/pipelines/${CI_PIPELINE_ID}/   \"}" ${rocket}
    - dep deploy prod -p -vv
  when: manual
  only:
    - master

rollback-prod:
  stage: rollback
  tags:
    - rozetka-shared-standart
  script:
    - curl -X POST -H "Content-Type:application/json" -d "{\"alias\":\"gitlab\",\"text\":\"* ${CI_PROJECT_NAME}:*   пользователь *${GITLAB_USER_LOGIN}* запустил откат  \nversion:*$CI_COMMIT_REF_NAME* \npipeline:${CI_PROJECT_URL}/pipelines/${CI_PIPELINE_ID}/   \"}" ${rocket}
    - dep rollback prod -p -vv
  allow_failure: true
  when: manual
  only:
    - master

stop-ms:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:stop prod -p -vv
  when: manual
  only:
    - master

stop-gs:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:stop prod -p -vv
  when: manual
  only:
    - master

restart-ms:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:stop prod -p -vv
    - dep consumers:ms:start prod -p -vv
  when: manual
  only:
    - master

restart-gs:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:stop prod -p -vv
    - dep consumers:gs:start prod -p -vv
  when: manual
  only:
    - master

start-ms:
  stage: start
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:start prod -p -vv
  when: manual
  only:
    - master

start-gs:
  stage: start
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:start prod -p -vv
  when: manual
  only:
    - master

jirabot:
  stage: report
  extends: .jirabot-template

include:
  - project: 'common/rozetka-pipelines'
    file: '/support/.jirabot-template.yml'

