image: registry.gitlab.rozetka.company/common/ci-docker-images/ci-deployer-php74:latest

before_script:
    - export VAULT_ADDR=https://vault.rozetka.company:8200
    - vault read -field=PROD_PRIVATE devops/infra/rzk > /root/.ssh/id_rsa 
    - chmod 600 /root/.ssh/id_rsa

stages:
  - deploy
  - rollback
  - stop-restart
  - start


deploy-dev:
  stage: deploy
  tags:
    - rozetka-shared-standart
  script:
    - consul-template -template "env.dev:.env" -once
    - dep build dev  -p -vv
    - dep deploy dev  -p -vv
  when: manual
  only:
    - branches
  except:
    - master


stop-dev-ms:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:stop dev -p -vv
  when: manual
  only:
    - branches
  except:
    - master


stop-dev-gs:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:stop dev -p -vv
  when: manual
  only:
    - branches
  except:
    - master

deploy-prod:
  stage: deploy
  tags:
    - rozetka-shared-standart
  script:
    - consul-template -template "env.prod:.env" -once
    - dep build prod -p -vv
    - curl -X POST -H "Content-Type:application/json" -d "{\"alias\":\"gitlab\",\"text\":\"* ${CI_PROJECT_NAME}:*   пользователь *${GITLAB_USER_LOGIN}* запустил деплой  \nversion:*$CI_COMMIT_REF_NAME* \npipeline:${CI_PROJECT_URL}/pipelines/${CI_PIPELINE_ID}/   \"}" ${rocket}
    - dep deploy prod -p -vv
  when: manual
  only:
    - master

rollback-prod:
  stage: rollback
  tags:
    - rozetka-shared-standart
  script:
    - curl -X POST -H "Content-Type:application/json" -d "{\"alias\":\"gitlab\",\"text\":\"* ${CI_PROJECT_NAME}:*   пользователь *${GITLAB_USER_LOGIN}* запустил откат  \nversion:*$CI_COMMIT_REF_NAME* \npipeline:${CI_PROJECT_URL}/pipelines/${CI_PIPELINE_ID}/   \"}" ${rocket}
    - dep rollback prod -p -vv
  allow_failure: true
  when: manual
  only:
    - master

stop-ms:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:stop prod -p -vv
  when: manual
  only:
    - master

stop-gs:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:stop prod -p -vv
  when: manual
  only:
    - master

restart-ms:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:stop prod -p -vv
    - dep consumers:ms:start prod -p -vv
  when: manual
  only:
    - master

restart-gs:
  stage: stop-restart
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:stop prod -p -vv
    - dep consumers:gs:start prod -p -vv
  when: manual
  only:
    - master

start-ms:
  stage: start
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:ms:start prod -p -vv
  when: manual
  only:
    - master

start-gs:
  stage: start
  tags:
    - rozetka-shared-standart
  script:
    - dep consumers:gs:start prod -p -vv
  when: manual
  only:
    - master
