image: registry.rozetka.company/ci:php7.4

before_script:
    - export VAULT_ADDR=https://vault.rozetka.company:8200
    - vault read -field=PROD_PRIVATE devops/infra/rzk > /root/.ssh/id_rsa 
    - chmod 600 /root/.ssh/id_rsa


stages:
  - deploy
  - stop-restart
  - start

deploy-dev:
  stage: deploy
  tags:
    - rozetka-shared
  script:
    - consul-template -template "env.dev:.env" -once
    - dep build dev  -p -vv
    - dep deploy dev  -p -vv
  when: manual
  only:
    - branches
  except:
    - master


stop-dev-ms:
  stage: stop
  tags:
    - rozetka-shared
  script:
    - dep consumers:ms:stop dev -p -vv
  when: manual
  only:
    - branches
  except:
    - master


stop-dev-gs:
  stage: stop
  tags:
    - rozetka-shared
  script:
    - dep consumers:gs:stop dev -p -vv
  when: manual
  only:
    - branches
  except:
    - master


deploy-prod:
  stage: deploy
  tags:
    - rozetka-shared
  script:
    - consul-template -template "env.prod:.env" -once
    - dep build prod -p -vv
    - dep deploy prod -p -vv
  when: manual
  only:
    - master

stop-ms:
  stage: stop-restart
  tags:
    - rozetka-shared
  script:
    - dep consumers:ms:stop prod -p -vv
  when: manual
  only:
    - master

stop-gs:
  stage: stop-restart
  tags:
    - rozetka-shared
  script:
    - dep consumers:gs:stop prod -p -vv
  when: manual
  only:
    - master

restart-ms:
  stage: stop-restart
  tags:
    - rozetka-shared
  script:
    - dep consumers:ms:stop prod -p -vv
    - dep consumers:ms:start prod -p -vv
  when: manual
  only:
    - master

restart-gs:
  stage: stop-restart
  tags:
    - rozetka-shared
  script:
    - dep consumers:gs:stop prod -p -vv
    - dep consumers:gs:start prod -p -vv
  when: manual
  only:
    - master

start-ms:
  stage: start
  tags:
    - rozetka-shared
  script:
    - dep consumers:ms:start prod -p -vv
  when: manual
  only:
    - master

start-gs:
  stage: start
  tags:
    - rozetka-shared
  script:
    - dep consumers:gs:start prod -p -vv
  when: manual
  only:
    - master